# dev-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-sa-rolebinding
  namespace: demo
subjects:
- kind: ServiceAccount
  name: dev-sa
  namespace: demo
roleRef:
  kind: Role
  name: developer-role
  apiGroup: rbac.authorization.k8s.io
