apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitor-binding
  namespace: demo
subjects:
- kind: ServiceAccount
  name: monitor-sa
  namespace: demo
roleRef:
  kind: Role
  name: monitor-role
  apiGroup: rbac.authorization.k8s.io
